---
- name: ASDlib | APIServerDemon lib directory
  file:
    path: "/root/APIServerDaemon/lib"
    state: directory
    mode: 0755

# Build GridCloudEngine threadpool
- name: gncTPool_bld | Build the GridnCloudEngine threadpool
  command: mvn clean install -Dmaven.compiler.source=1.6 -Dmaven.compiler.target=1.6
  args:
    chdir: "/root/grid-and-cloud-engine/grid-and-cloud-engine-threadpool"
    creates: "/root/grid-and-cloud-engine/grid-and-cloud-engine-threadpool/target/grid-and-cloud-engine-threadpool-0.0.1-SNAPSHOT.jar"
  register: gnceng_tp
# Stat grid-and-cloud-engine-threadpool-0.0.1-SNAPSHOT.jar
- name: gnceng_thrpool.jar | Stat grid-and-cloud-engine-threadpool-0.0.1-SNAPSHOT.jar
  stat:
    path: "/root/APIServerDaemon/lib/grid-and-cloud-engine-threadpool-0.0.1-SNAPSHOT.jar"
  register: gnceng_tp_jar
# Place GridnCloudEngine threadpool jar into APIServerdaemon lib/
- name: gncTPool_cpy | Copy the GridnCloudEngine threadpool jar to APIServerDaemon lib directory
  copy:
    remote_src: true
    src: "/root/grid-and-cloud-engine/grid-and-cloud-engine-threadpool/target/grid-and-cloud-engine-threadpool-0.0.1-SNAPSHOT.jar"
    dest: "/root/APIServerDaemon/lib/grid-and-cloud-engine-threadpool-0.0.1-SNAPSHOT.jar"
    mode: 0644
  when: gnceng_tp.changed or not gnceng_tp_jar.stat.exists
# Place GridnCloudEngine threadpool lib/ content into APIServerdaemon lib/
# - name: gncTPool_lib | Copy the GridnCloudEngine threadpool lib/ content to APIServerDaemon lib directory
#   copy:
#     remote_src: true
#     src: "/root/grid-and-cloud-engine/grid-and-cloud-engine-threadpool/target/lib/"
#     dest: "/root/APIServerDaemon/lib/"
#     recurse: true
#   when: gnceng_tp.changed or not gnceng_tp_jar.stat.exists

# Build GridnCloudEngine main classes
- name: gncMain_bld | Build the GridnCloudEngine main classes
  command: mvn clean install -Dmaven.compiler.source=1.6 -Dmaven.compiler.target=1.6
  args:
    chdir: "/root/grid-and-cloud-engine/grid-and-cloud-engine_M"
    creates: "/root/grid-and-cloud-engine/grid-and-cloud-engine_M/target/grid-and-cloud-engine_M-0.0.1-SNAPSHOT.jar"
  register: gnceng_M

# - name: gncMain_cpy | Copy the GridnCloudEngine main jar to APIServerDaemon lib directory
#   copy:
#     src: "/root//grid-and-cloud-engine/grid-and-cloud-engine_M/target/grid-and-cloud-engine_M-0.0.1-SNAPSHOT.jar"
#     dest: "/root/APIServerDaemon/lib/grid-and-cloud-engine_M-0.0.1-SNAPSHOT.jar"
#     mode: 0644
#   when: gnceng_M.changed or not gnceng_m_jar.stat.exists
#
# # Place GridnCloudEngine main lib/ content into APIServerdaemon lib/
# - name: gncMain_lib | Copy the GridnCloudEngine main lib/ content to APIServerDaemon lib directory
#   copy:
#     src: "/root//grid-and-cloud-engine/grid-and-cloud-engine_M/target/lib/"
#     dest: "/root/APIServerDaemon/lib/"
#     mode: 0644
#   when: gnceng_M.changed or not gnceng_m_jar.stat.exists
