---
#
# Baseline configuration
#

#
# Configure FutureGateway DB accordingly to the tester user
#
# FutureGateway provides a helloworld and sayhello default applications
# in order to use them the infrastructure settings must be changed
# with the APIServerDaemon tester user credentials
#

# Configure the SSH infrastructure host parameter
# Configure the SSH infrastructure user parameter
#when: only 1st time APIServerDaemon installs
# Configure the SSH infrastructure user password parameter
#when: only 1st time APIServerDaemon installs
