---
- name: Ensure python apt interface
  package:
    name: python-apt
    state: present

- name: Add keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{apt_keys}}"

- name: Add repositories
  apt_repository:
    repo: "{{ item.repo}}"
    filename: "{{ item.filename}}"
  with_items: "{{apt_repos}}"
